import React from "react";
import {
  SiReact,
  SiNextdotjs,
  SiMui,
  SiTailwindcss,
  SiTypescript,
  SiJquery,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiMysql,
  SiPostgresql,
  SiFirebase,
  SiSupabase,
  SiMongodb,
  SiGit,
  SiGithub,
  SiGitlab,
  SiAmazonwebservices,
  SiVercel,
  SiDocker,
  SiGithubactions
} from "react-icons/si";

export const skillIconMap: Record<string, { icon: React.ComponentType<{ className?: string }>, color: string }> = {
  React: { icon: SiReact, color: "text-gray-500" },
  "Next.js": { icon: SiNextdotjs, color: "text-gray-500" },
  MUI: { icon: SiMui, color: "text-gray-500" },
  "Tailwind CSS": { icon: SiTailwindcss, color: "text-gray-500" },
  TypeScript: { icon: SiTypescript, color: "text-gray-500" },
  jQuery: { icon: SiJquery, color: "text-gray-500" },
  "Node.js": { icon: SiNodedotjs, color: "text-gray-500" },
  "Express.js": { icon: SiExpress, color: "text-gray-500" },
  NestJS: { icon: SiNestjs, color: "text-gray-500" },
  MySQL: { icon: SiMysql, color: "text-gray-500" },
  PostgreSQL: { icon: SiPostgresql, color: "text-gray-500" },
  Firebase: { icon: SiFirebase, color: "text-gray-500" },
  Supabase: { icon: SiSupabase, color: "text-gray-500" },
  MongoDB: { icon: SiMongodb, color: "text-gray-500" },
  Git: { icon: SiGit, color: "text-gray-500" },
  GitHub: { icon: SiGithub, color: "text-gray-500" },
  GitLab: { icon: SiGitlab, color: "text-gray-500" },
  AWS: { icon: SiAmazonwebservices, color: "text-gray-500" },
  Vercel: { icon: SiVercel, color: "text-gray-500" },
  Docker: { icon: SiDocker, color: "text-gray-500" },
  "GitHub Actions": { icon: SiGithubactions, color: "text-gray-500" },
};

export const skillCategories = {
  Frontend: ["React", "Next.js", "MUI", "Tailwind CSS", "TypeScript", "jQuery"],
  Backend: ["Node.js", "Express.js", "NestJS"],
  Database: ["MySQL", "PostgreSQL", "Firebase", "Supabase", "MongoDB"],
  "Other Tools": ["Git", "GitHub", "GitLab", "AWS", "Vercel", "Docker", "GitHub Actions"],
};
